### ISSUE TITLE
Exception in the script at not detected when running pulumi directly

### ISSUE THREAD

**Issue by rdbartram** [worxspace/PSPulumi#1]

**Comment by rdbartram** [comment]
Ok, so after looking at this, the best way to resolve this is to do one of the following:

1. set `$ExecutionActionPreference = 'stop'` at the top of your script
2. adjust your pspulumi.yaml as follows

```yaml
name: psyamlpulumi
runtime:
  name: yaml
  options:
    compiler: pwsh -noninteractive -noprofile -command "& {$ErrorActionPreference='stop'; ./powershell.ps1}"
```
